### ISSUE TITLE
Question regarding replication and Data acces

### ISSUE THREAD

**Issue by jakubhajko** [volvox292/mass2smiles#1]
Hello! We are attempting to replicate the evaluation as reported in your article and have a few questions. We would greatly appreciate your help!

- Is it possible to get access to the DataFrame `data_df` from `substructure_1.1v.ipynb` (or at least to the `spectrum_id` column for the commercial NIST20)? Unfortunately, we were unable to find it on Zenodo, but it is essential to keep the evaluation consistent.

- Have we correctly understood that the first column in the `val_result_5l_50ep_misunderstood` sheet of `S2_val_results.xlsx` corresponds to the subset of `spectrum_id` values from `data_df`?

- When reporting the performance on CASMI, have you excluded the InChI keys of CASMI molecules from the training data (similarly to the evaluation on the validation fold)?

Thank you in advance!

**Comment by volvox292** [comment]
Hi Levoslav,

Sorry for the late reply I am just getting used to my new job here after long holidays. I can't give you access to the dataframe due to copyright. I may be able to get ID column for you with InChI keys, but I need some more time to retrieve and copy my old data. 

Yes this is the validation dataset, these were not included in the training. 

I initially assumed that CASMI molecules should not be present within any database, that's why I did not look to exclude the corresponding InChI for training, I only later found out that this was not entirely true (there are 1 or 2 overlaps), but you can check it out soon when I manage to prepare the dataframe columns for you.

**Comment by roman-bushuiev** [comment]
HI, @volvox292! Thanks for the information. It would be great if you could provide IDs, looking forward to it. (I work with Levoslav.)

**Comment by volvox292** [comment]
I just uploaded the IDs for you.
